<?php
use Illuminate\Support\Facades\Route; use App\Http\Controllers\Api\AuthController; use App\Http\Controllers\Api\FormsController; use App\Http\Controllers\Api\WebApiController; use App\Http\Controllers\Api\MediaController;
Route::prefix('v1/web')->group(function(){
 Route::get('pages', [WebApiController::class,'pages']); Route::get('pages/{slug}',[WebApiController::class,'page']); Route::get('news',[WebApiController::class,'news']); Route::get('team',[WebApiController::class,'team']); Route::get('board',[WebApiController::class,'board']); Route::get('sponsors',[WebApiController::class,'sponsors']); Route::get('menus/{location?}',[WebApiController::class,'menus']); Route::get('settings',[WebApiController::class,'settings']);
 Route::middleware('throttle:10,1')->post('forms/{type}',[FormsController::class,'store']);
 Route::post('auth/login',[AuthController::class,'login'])->middleware('throttle:10,1'); Route::post('auth/forgot-password',[AuthController::class,'forgot'])->middleware('throttle:5,1'); Route::post('auth/reset-password',[AuthController::class,'reset']);
 Route::middleware(['auth:sanctum','audience:web'])->group(function(){Route::post('auth/logout',[AuthController::class,'logout']);Route::get('auth/me',[AuthController::class,'me']);Route::post('auth/change-password',[AuthController::class,'changePassword']);Route::post('auth/2fa/setup',[AuthController::class,'twoFactorSetup']);Route::post('auth/2fa/confirm',[AuthController::class,'twoFactorConfirm']);Route::post('auth/2fa/disable',[AuthController::class,'twoFactorDisable']);
  Route::prefix('admin')->middleware('permission:web.admin')->group(function(){Route::get('dashboard',[WebApiController::class,'dashboard']);Route::get('users',[WebApiController::class,'users']);Route::patch('users/{user}',[WebApiController::class,'updateUser']);Route::get('audit',[WebApiController::class,'audit']);Route::get('media',[WebApiController::class,'media']);Route::post('media',[MediaController::class,'upload']);Route::delete('media/{media}',[MediaController::class,'destroy']);Route::get('media/{media}/url',[MediaController::class,'url']);Route::get('forms',[WebApiController::class,'forms']);Route::post('cache/invalidate',[WebApiController::class,'invalidateCache']);});
 });
});
