<?php
namespace Tests\Feature; use App\Models\{Product,Inventory}; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Str; use Illuminate\Support\Facades\Http; use Tests\TestCase;
class StorePhase6Test extends TestCase { use RefreshDatabase; protected function setUp():void{parent::setUp();Http::fake(['*'=>Http::response(['id'=>'pay-1','status'=>'pending'],201)]);}
 private function product(int $stock=1):Product{$p=Product::create(['name'=>'Camiseta','slug'=>'camiseta-'.Str::random(5),'sku'=>'SKU'.Str::random(5),'price'=>4500,'status'=>'active']);Inventory::create(['product_id'=>$p->id,'available'=>$stock]);return $p;}
 public function test_catalog_and_valid_sale_price():void{$p=$this->product();$p->update(['sale_price'=>3000,'sale_starts_at'=>now()->subDay(),'sale_ends_at'=>now()->addDay()]);$this->getJson('/api/v1/store/products/'.$p->slug)->assertOk()->assertJsonPath('display_price',3000);}
 public function test_expired_sale_uses_regular_price():void{$p=$this->product();$p->update(['sale_price'=>1000,'sale_starts_at'=>now()->subDays(2),'sale_ends_at'=>now()->subDay()]);$this->getJson('/api/v1/store/products/'.$p->slug)->assertOk()->assertJsonPath('display_price',4500);}
 public function test_checkout_is_idempotent_and_reserves_stock():void{$p=$this->product();$cart=$this->getJson('/api/v1/store/cart')->json();$this->withHeaders(['X-Cart-Token'=>$cart['token']])->postJson('/api/v1/store/cart/items',['cart_token'=>$cart['token'],'product_id'=>$p->id,'quantity'=>1])->assertOk();$h=['Idempotency-Key'=>'order-1'];$a=$this->withHeaders($h)->postJson('/api/v1/store/checkout',['cart_token'=>$cart['token'],'email'=>'a@example.com','consent'=>'1'])->assertCreated();$b=$this->withHeaders($h)->postJson('/api/v1/store/checkout',['cart_token'=>$cart['token'],'email'=>'a@example.com','consent'=>'1'])->assertOk();$this->assertSame($a->json('order.public_id'),$b->json('public_id')??$b->json('order.public_id'));$this->assertSame(1,Inventory::first()->reserved);}
 public function test_stock_never_negative():void{$p=$this->product(0);$cart=$this->getJson('/api/v1/store/cart')->json();$this->withHeaders(['X-Cart-Token'=>$cart['token']])->postJson('/api/v1/store/cart/items',['cart_token'=>$cart['token'],'product_id'=>$p->id,'quantity'=>1])->assertStatus(409);}
}
