<?php
namespace App\Http\Controllers; use App\Models\{Product,Cart,CartItem,Order,OrderItem,Inventory}; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Http; use Illuminate\Support\Str;
class StoreController extends Controller {
 public function products(Request $r){$q=Product::with('inventory')->where('status','active');if($r->filled('q'))$q->where('name','like','%'.$r->q.'%');if($r->filled('category_id'))$q->where('category_id',$r->category_id);return $q->paginate(24);}
 public function product(string $slug){$p=Product::with('inventory')->where('slug',$slug)->where('status','active')->firstOrFail();$p->display_price=$p->effectivePrice();return $p;}
 public function cart(Request $r){$token=$r->header('X-Cart-Token');$c=$token?Cart::with('items.product')->where('token',$token)->first():null;if(!$c||$c->expires_at->isPast()){$c=Cart::create(['token'=>(string)Str::uuid(),'expires_at'=>now()->addHours(24)]);}return response()->json($c->load('items.product'));}
 public function addCart(Request $r){$d=$r->validate(['cart_token'=>'required|uuid','product_id'=>'required|exists:products,id','quantity'=>'required|integer|min:1|max:99']);$c=Cart::where('token',$d['cart_token'])->where('expires_at','>',now())->firstOrFail();$p=Product::findOrFail($d['product_id']);$i=Inventory::where('product_id',$p->id)->lockForUpdate()->firstOrFail();abort_if($i->availableToSell()<$d['quantity'],409,'Stock insuficiente.');CartItem::updateOrCreate(['cart_id'=>$c->id,'product_id'=>$p->id],['quantity'=>$d['quantity'],'unit_price'=>$p->effectivePrice()]);return $c->load('items.product');}
 public function checkout(Request $r){$d=$r->validate(['cart_token'=>'required|uuid','email'=>'required|email','shipping'=>'nullable|array','consent'=>'accepted']);$key=$r->header('Idempotency-Key');abort_unless($key,400,'Idempotency-Key requerido.');$existing=Order::where('correlation_id',$key)->first();if($existing)return response()->json($existing->load('items'));$order=DB::transaction(function()use($d,$r,$key){$c=Cart::with('items.product')->where('token',$d['cart_token'])->lockForUpdate()->firstOrFail();$subtotal=0;foreach($c->items as $item){$i=Inventory::where('product_id',$item->product_id)->lockForUpdate()->firstOrFail();abort_if($i->availableToSell()<$item->quantity,409,'Stock insuficiente.');$i->increment('reserved',$item->quantity);$subtotal+=$item->quantity*$item->product->effectivePrice();}$o=Order::create(['public_id'=>(string)Str::uuid(),'status'=>'pending_payment','email'=>$d['email'],'shipping'=>$d['shipping']??null,'subtotal'=>$subtotal,'total'=>$subtotal,'currency'=>$c->currency,'correlation_id'=>$key]);foreach($c->items as $item)OrderItem::create(['order_id'=>$o->id,'product_id'=>$item->product_id,'quantity'=>$item->quantity,'unit_price'=>$item->product->effectivePrice()]);return $o;});$payment=Http::withHeaders(['X-Service-Token'=>config('store.payments_token'),'X-Service-Audience'=>'store','X-Service-Scopes'=>'payments.write','Idempotency-Key'=>$key])->post(rtrim(config('store.payments_url'),'/').'/internal/v1/payment-intents',['source'=>'store','external_reference'=>$order->public_id,'amount'=>$order->total,'currency'=>$order->currency]);if($payment->successful())$order->update(['payment_public_id'=>$payment->json('id')]);return response()->json(['order'=>$order,'payment'=>$payment->json()],201);}
 public function paymentEvent(Request $r){$d=$r->validate(['event_type'=>'required|string','payment_id'=>'required|string','order_id'=>'required|string']);$o=Order::where('public_id',$d['order_id'])->firstOrFail();if($d['event_type']==='payment.succeeded')$o->update(['status'=>'paid']);elseif(in_array($d['event_type'],['payment.failed','payment.cancelled'],true)){DB::transaction(function()use($o){foreach($o->items as $item)Inventory::where('product_id',$item->product_id)->decrement('reserved',$item->quantity);$o->update(['status'=>'failed']);});}return ['accepted'=>true];}
 public function order(string $id){return Order::with('items')->where('public_id',$id)->firstOrFail();}
}
